version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: r3dev-stack
      POSTGRES_PASSWORD: r3dev-stack
      POSTGRES_DB: r3dev-stack
    ports:
      - 5432:5432

volumes:
  pg-data: